### ISSUE TITLE
!userconf command can be abused to ping people

### ISSUE THREAD

**Issue by pixelomer** [Emy/janet#74]
Here's a **successful** attempt:

![Successful user mention](https://user-images.githubusercontent.com/37103802/87873048-c25ffe80-c9c6-11ea-9c43-f947b9dc0ab8.png)

If Janet had the required permissions it could be abused to mention roles too, but that's not possible with the current permissions. Here's a **failed** attempt:

![Failed role mention](https://user-images.githubusercontent.com/37103802/87873074-f1767000-c9c6-11ea-8b8f-17653d7157f1.png)

**Comment by Emy** [comment]
We have disabled the userconf command globally because it has no real use in our case. Thanks for reporting!
