### ISSUE TITLE
[Bug] !userconf can be abused to bypass all filters

### ISSUE THREAD

**Issue by pixelomer** [Emy/janet#78]
`!userconf show <message>` can be abused to send any message and bypass all of the filters. The only limitation is that the message cannot contain an ASCII whitespace (0x20).

![Screenshot](https://user-images.githubusercontent.com/37103802/92797746-04039900-f3bb-11ea-8e04-d8e3ffeb2ca2.png)

**Comment by Emy** [comment]
This is definitely unintended behavior for us that is caused by relying on third party code with different intended behavior. Good catch!
