### ISSUE TITLE
[Bug] !removedevice can be abused to bypass filters

### ISSUE THREAD

**Issue by pixelomer** [Emy/janet#81]
Steps to reproduce (each line is a different message):

```
/nick x`||Spoiler||`x [ ,.]
!removedevice
```

**Comment by n3oney** [comment]
End result is the same as if you would've just done
`/nick x`||Spoiler||`x `
Is it worth fixing?

**Comment by pixelomer** [comment]
> End result is the same as if you would've just done
> 
> ```
> /nick x`||Spoiler||`x
> ```
> 

It is not. Yes, your nickname becomes x\`||Spoiler||\`x but also Janet sends a message with the line below.

https://github.com/Emy/janet/blob/52f8f070998a1493dd355cbca7a6d569b355e0e7/src/commands/Information/removedevice.ts#L22

This way you are able to bypass the spoiler filter with your new nickname. Not a serious issue but I think it still is an issue.

**Comment by Emy** [comment]
@pixelomer Thanks for reporting. 
Also might only be an Issue for people with the Member Pro Role right?

cc/ @1Conan any idea how we are wanting to handle this issue?
